{ pkgs, ... }:

let
  # Pywal templates
  clipse-template = pkgs.writeText "clipse_theme.json" /* json */ ''
    {{
     "UseCustom":          true,
     "TitleFore":          "{foreground}",
     "TitleBack":          "{color5}",
     "TitleInfo":          "{color4}",
     "NormalTitle":        "{foreground}",
     "DimmedTitle":        "{color8}",
     "SelectedTitle":      "{color1}",
     "NormalDesc":         "{color8}",
     "DimmedDesc":         "{color8}",
     "SelectedDesc":       "{color1}",
     "StatusMsg":          "{color2}",
     "PinIndicatorColor":  "{color3}",
     "SelectedBorder":     "{color4}",
     "SelectedDescBorder": "{color4}",
     "FilteredMatch":      "{foreground}",
     "FilterPrompt":       "{color2}",
     "FilterInfo":         "{color4}",
     "FilterText":         "{foreground}",
     "FilterCursor":       "{color3}",
     "HelpKey":            "{color8}",
     "HelpDesc":           "{color8}",
     "PageActiveDot":      "{color4}",
     "PageInactiveDot":    "{color8}",
     "DividerDot":         "{color4}",
     "PreviewedText":      "{foreground}",
     "PreviewBorder":      "{color4}"
    }}
  '';

  superfile-template = pkgs.writeText "superfile.toml" /* toml */ ''
    # Generated by pywal
    # Superfile Theme

    # ========= Border =========
    file_panel_border = '{color8}'
    sidebar_border = '{background}'
    footer_border = '{color8}'

    # ========= Border Active =========
    file_panel_border_active = '{color4}'
    sidebar_border_active = '{color1}'
    footer_border_active = '{color2}'
    modal_border_active = '{color7}'

    # ========= Background (bg) =========
    full_screen_bg = '{background}'
    file_panel_bg = '{background}'
    sidebar_bg = '{background}'
    footer_bg = '{background}'
    modal_bg = '{background}'

    # ========= Foreground (fg) =========
    full_screen_fg = '{foreground}'
    file_panel_fg = '{foreground}'
    sidebar_fg = '{foreground}'
    footer_fg = '{foreground}'
    modal_fg = '{foreground}'

    # ========= Special Color =========
    cursor = '{cursor}'
    correct = '{color2}'
    error = '{color1}'
    hint = '{color4}'
    cancel = '{color5}'
    gradient_color = ['{color4}', '{color6}']

    # ========= File Panel Special Items =========
    file_panel_top_directory_icon = '{color2}'
    file_panel_top_path = '{color4}'
    file_panel_item_selected_fg = '{color4}'
    file_panel_item_selected_bg = '{background}'

    # ========= Sidebar Special Items =========
    sidebar_title = '{color4}'
    sidebar_item_selected_fg = '{color4}'
    sidebar_item_selected_bg = '{background}'
    sidebar_divider = '{color7}'

    # ========= Modal Special Items =========
    modal_cancel_fg = "#383838"
    modal_cancel_bg = '{color5}'
    modal_confirm_fg = "#383838"
    modal_confirm_bg = '{color6}'
  '';

in
{
  home.packages = with pkgs; [
    pywal
    imagemagick
  ];

  home.file = {
    ".config/wal/templates/clipse_theme.json".source = clipse-template;
    ".config/wal/templates/superfile.toml".source    = superfile-template;
  };
}

